config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root 'home#index'
  # DEVISE STUFF
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # UPDATE USER
  resources :users, only: [:edit, :update]
  # HOME CONTROLLER
  resources :home, only: [:index] do
    collection do
      post :index
    end
  end
  get 'about_us', to: 'home#about_us', as: :about_us
  get 'contact_us', to: 'home#contact_us', as: :contact_us
  # STORY ACTIONS
  resources :stories, only: [] do
    collection do
      get :view
    end
    member do
      post :save
      post :forget
    end
  end
  resources :sessions, only: :toggle_sidebar_state do
    collection do
      post :toggle_sidebar_state
    end
  end
  # MY STORIES
  get 'my_stories', to: 'stories#my_stories'
  # ADMIN ROUTES
  namespace :admin do
    resources :initialize_scraper, only: [:index] do
      collection do
        get :scrape
      end
    end
    resources :stories, only: [:index, :show, :destroy] do
      member do
        get :images
        post :images_update
        get :review
        patch :review_update
        patch :update_state
      end

      collection do
        get :bulk_index
        post :bulk_update
      end
    end
    resources :media_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :video_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :custom_stories, except: [:index, :destroy] do
      member do
        post :destroy_image
        get :list_editor
        get :list_edit
        patch :update_list
        get :review
        patch :review_update
      end
    end
    resources :urls, except: [:show]
    resources :images, except: [:show]
    resources :codes, except: [:show]
    resources :story_regions, except: [:show]
    resources :place_groupings, except: [:show]
    resources :story_categories, except: [:show]
    resources :media_owners, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :bulk_update
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :export_allstories
        get :export_stories
        get :export_images
        get :export_mediaowners
        get :export_usersaved
        get :export_userlisting
        get :export_all
        get :export_newsfeed_activities
      end
    end
    resources :published_items, except: [:show] do
      member do
        post :display
        post :unpublish
        post :add_to_queue
      end
    end
    resources :newsfeed, only: [:edit, :update] do
      member do
        post :remove
        post :publish
      end

      collection do
        get :queue
        get :activities
      end
    end
    resources :admin_settings, only: [:index, :update]
  end

  # redirect to home if route doesn't exist
  if Rails.env.production?
    match '*path', via: :all, to: 'home#index', constraints: lambda { |req|
      # NEED THIS HERE FOR ACTIVE STORAGE IMAGES TO SHOW UP
      req.path.exclude? 'rails/active_storage'
    }
  end
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  attr_accessor :story_id

  belongs_to :location
  belongs_to :category, optional: true
  belongs_to :place_status_option, optional: true

  accepts_nested_attributes_for :location, reject_if: :all_blank

  has_many :story_places, dependent: :destroy
  has_many :stories, through: :story_places

  validates :name, presence: true

  include PgSearch::Model
  pg_search_scope :search,
                  against: [:name],
                  using: { tsearch: {any_word: true, prefix: true} }

end

app/controllers/admin/places_controller.rb
# frozen_string_literal: true

module Admin
  class PlacesController < Admin::BaseAdminController
    before_action :set_place, except: %i[index search new create]
    before_action :check_for_admin, only: :destroy

    def index
      @places = Place.order(created_at: :desc)
      @pagy, @places = pagy(@places)
    end

    def show
      @comments = Comment.where(reference: 'place', reference_id: @place.id)
    end

    def new
      @place = Place.new
      @place.build_location
    end

    def create
      @place = Place.new(place_params)
      if @place.save
        if params[:place][:story_id]
          StoryPlace.create(story_id: params[:place][:story_id], place_id: @place.id)
          redirect_to places_admin_story_path(params[:place][:story_id])
        else
          redirect_to admin_place_path(@place)
        end
      else
        redirect_to new_admin_place_path, alert: 'Could not create Place.'
      end
    end

    def edit; end

    def update
      if @place.update(place_params)
        redirect_to admin_place_path(@place), notice: 'Successfully updated Place.'
      else
        redirect_to admin_place_path(@place), alert: 'Could not update Place.'
      end
    end

    def destroy
      if @place.destroy
        redirect_to admin_places_path, notice: 'Successfully destroyed Place.'
      else
        redirect_to admin_places_path, alert: 'Could not destroy Place.'
      end
    end

    private

    def set_place
      @place = Place.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_places_path
    end

    def place_params
      params.require(:place).permit!
    end
  end
end

app/views/admin/places/_form.html.erb
<%= form_for([:admin, @place]) do |f| %>
  <div class="jumbotron bg-white admin-form">
    <div class="header text-center">
      <h4><i class="fas fa-map-marker-alt mr-1"></i> Add Place</h4>
    </div>

    <hr class="my-4">

    <div class="body">

      <% if params[:story_id] %>
        <%= f.hidden_field :story_id, value: params[:story_id] %>
      <% end %>

      <div class="form-group my-4 max-vw-80 mx-auto">
        <%= f.label "Status" %><br>
        <%= f.collection_select(:place_status_option_id, PlaceStatusOption.order(:id), :id, :name, :prompt => true, class: "form-control") %>
      </div>

      <div class="form-group my-4 max-vw-80 mx-auto">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

         <div class="form-group my-4 max-vw-80 mx-auto">
          <label>Select a category:</label>
          <select id="category-roots">
            <option value="">- Please Select -</option>
            <% Category.places.roots.each do |c| %>
              <option value="<%= c.id %>"><%= c.name %></option>
            <% end %>
          </select>
         </div>

        <div class="form-group my-4 max-vw-80 mx-auto">
          <select id="second-level-categories">
           <option value="">- Please Select -</option>
          </select>
         </div>

        <div class="form-group my-4 max-vw-80 mx-auto">
          <select id="third-level-categories">
            <option value="">- Please Select -</option>
          </select>
        </div>

        Selected Category: <span id="selected-name"></span><br>
    
      <%= f.hidden_field :category_id, id: "selected-id", value: "" %>

       <%= f.fields_for :location do |a| %>
        <%= render 'admin/locations/fields', f: a %>
      <% end %>

      <div class="actions">
        <%= f.submit "Save", class: 'btn btn-md btn-primary text-center w-100' %>
      </div>
    </div>

  </div>
<% end %>

app/views/admin/places/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/admin/places/index.html.erb
<div class="container-fluid">
  <div class="links mb-2 text-right">
    <%= link_to new_admin_place_path, class: "btn btn-sm btn-success" do %>
      <i class="fas fa-plus mr-1"></i> Add Place
    <% end %>
  </div>
  <div class="jumbotron bg-white admin-index-page">
    <div class="header text-center">
      <h4><i class="fas fa-map-marker-alt mr-1"></i> Places</h4>
    </div>

    <hr class="my-4">

    <div class="table-div">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col">Created At</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @places.each do |place| %>
            <tr>
              <td><%= place.id %></td>
              <td><%= place.name %></td>
              <td>
                <% if place.category %>
                 <% if place.category.ancestors %>
                  <% place.category.ancestors.each do |c| %>
                    <%= c.name %> >
                  <% end %>
               <% end %>
                <%= link_to place.category.name, admin_category_path(place.category) %>
               <% end %>
              </td>
              <td><%= pretty_date_format(place.created_at) %></td>
              <td class="action-links">
                  <%= link_to admin_place_path(place), class: "btn btn-sm btn-outline-success" do %>
                  <i class="fas fa-eye"></i>
                <% end %>
                <%= link_to edit_admin_place_path(place), class: "btn btn-sm btn-outline-warning" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to admin_place_path(place), method: :delete, class: "btn btn-sm btn-outline-danger delete-link", data: { confirm: 'Are you sure?' }, target: '_blank' do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr class="my-4">

    <div class='pagination'>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>

  </div>
</div>

app/views/admin/places/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/admin/places/show.html.erb
<div class="container-fluid">
  <div class="links mb-2 text-right">
    <%= link_to "#add-comment", class: "btn btn-sm btn-primary", data: {toggle: "collapse"} do %>
      <i class="fas fa-sticky-note mr-1"></i> Add Comment
    <% end %>
    <%= link_to edit_admin_place_path(@place), class: "btn btn-sm btn-success" do %>
      <i class="fas fa-edit mr-1"></i> Edit Place
    <% end %>
  </div>

<div class="collapse" id="add-comment">
    <%= render 'admin/comments/form', reference: "place", reference_id: @place.id %>
</div>

  <div class="jumbotron bg-white admin-index-page">
    <div class="header text-center">
      <h4><i class="fas fa-map-marker-alt mr-1"></i> <%= @place.name %></h4>
    </div>

    <hr class="my-4">

     Status:  <%= @place.place_status_option.name %><br>
     Category:  
    <% if @place.category %>
      <% if @place.category.ancestors %>
        <% @place.category.ancestors.each do |c| %>
          <%= c.name %> >
        <% end %>
      <% end %>
      <%= link_to @place.category.name, admin_category_path(@place.category) %><br>
    <% end %>
   
   
    <% if @place.location %>
    Location: 
      <%= @place.location.full_address %><br>
  <br>
       <div id="map"></div>
 <script>
    var lat = <%= @place.location.latitude %>
    var long = <%= @place.location.longitude %>
    var mymap = L.map('map').setView([lat,long], 15);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
      maxZoom: 18,
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
        'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1
    }).addTo(mymap);

    L.marker([lat, long]).addTo(mymap)
		.bindPopup("<b><%= @place.name %>").openPopup();

	  var popup = L.popup();
</script>

    <% end %>

    
    <div class="mt-4 header text-center">
      <h4><i class="fas fa-book mr-1"></i>Stories</h4>
    </div>
      <hr class="my-4">
    <% if @place.stories.any? %>
      <% @place.stories.each do |story| %>
        <div class="row">
          <div class="col-2"><%= story.story_display_date %></div>
          <div class="col-8"><%= link_to story.display_title, admin_story_path(story.id), target: '_blank' %></div>
        </div>
      <% end %>
    <% else %>
      <p class="no-stories-text">No Stories Found</p>
    <% end %>

    <%= render 'admin/comments/comments', comments: @comments %>

  </div>

</div>