config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root 'home#index'
  # DEVISE STUFF
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # UPDATE USER
  resources :users, only: [:edit, :update]
  # HOME CONTROLLER
  resources :home, only: [:index] do
    collection do
      post :index
    end
  end
  get 'about_us', to: 'home#about_us', as: :about_us
  get 'contact_us', to: 'home#contact_us', as: :contact_us
  # STORY ACTIONS
  resources :stories, only: [] do
    collection do
      get :view
    end
    member do
      post :save
      post :forget
    end
  end
  resources :sessions, only: :toggle_sidebar_state do
    collection do
      post :toggle_sidebar_state
    end
  end
  # MY STORIES
  get 'my_stories', to: 'stories#my_stories'
  # ADMIN ROUTES
  namespace :admin do
    resources :initialize_scraper, only: [:index] do
      collection do
        get :scrape
      end
    end
    resources :stories, only: [:index, :show, :destroy] do
      member do
        get :images
        post :images_update
        get :review
        patch :review_update
        patch :update_state
      end

      collection do
        get :bulk_index
        post :bulk_update
      end
    end
    resources :media_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :video_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :custom_stories, except: [:index, :destroy] do
      member do
        post :destroy_image
        get :list_editor
        get :list_edit
        patch :update_list
        get :review
        patch :review_update
      end
    end
    resources :urls, except: [:show]
    resources :images, except: [:show]
    resources :codes, except: [:show]
    resources :story_regions, except: [:show]
    resources :place_groupings, except: [:show]
    resources :story_categories, except: [:show]
    resources :media_owners, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :bulk_update
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :export_allstories
        get :export_stories
        get :export_images
        get :export_mediaowners
        get :export_usersaved
        get :export_userlisting
        get :export_all
        get :export_newsfeed_activities
      end
    end
    resources :published_items, except: [:show] do
      member do
        post :display
        post :unpublish
        post :add_to_queue
      end
    end
    resources :newsfeed, only: [:edit, :update] do
      member do
        post :remove
        post :publish
      end

      collection do
        get :queue
        get :activities
      end
    end
    resources :admin_settings, only: [:index, :update]
  end

  # redirect to home if route doesn't exist
  if Rails.env.production?
    match '*path', via: :all, to: 'home#index', constraints: lambda { |req|
      # NEED THIS HERE FOR ACTIVE STORAGE IMAGES TO SHOW UP
      req.path.exclude? 'rails/active_storage'
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"

  before_action :set_limit, only: :index
  before_action :filter_out_file_types_from_url, only: :index

  def index
    # database dropdown data
    @story_regions    = StoryRegion.order("ascii(name)")
    @place_groupings  = PlaceGrouping.order(:name)
    @story_categories = StoryCategory.order(:name)

    @published_items = PublishedItem.joins("
      INNER JOIN stories ON (publishable_type = 'Story' AND stories.id = publishable_id)
      LEFT JOIN stories_users ON stories_users.story_id = stories.id
      LEFT JOIN stories_story_regions ON stories_story_regions.story_id = stories.id
      LEFT JOIN story_regions ON story_regions.id = stories_story_regions.story_region_id
      LEFT JOIN place_groupings_stories ON place_groupings_stories.story_id = stories.id
      LEFT JOIN place_groupings ON place_groupings.id = place_groupings_stories.place_grouping_id
      LEFT JOIN story_story_categories ON story_story_categories.story_id = stories.id
      LEFT JOIN story_categories ON story_categories.id = story_story_categories.story_category_id
    ").select('published_items.*, stories.*, stories_users.created_at AS save_date')

    if params[:story_region_id].present? || params[:place_grouping_id].present? || params[:story_category_id].present?
      @published_items = @published_items.where(story_regions: { id: params[:story_region_id] }) if params[:story_region_id].present?
      @published_items = @published_items.where(place_groupings: { id: params[:place_grouping_id] }) if params[:place_grouping_id].present?
      @published_items = @published_items.where(story_categories: { id: params[:story_category_id] }) if params[:story_category_id].present?
      @published_items = @published_items.limit(AdminSetting.filtered_display_limit)
      @published_items = @published_items.order(created_at: :desc)
    else
      @published_items = @published_items.where(state: 'newsfeed').limit(AdminSetting.newsfeed_display_limit)
      @published_items = @published_items.order(pinned: :desc, posted_at: :desc)
    end

    @published_items = @published_items.distinct
  end

  def about_us
  end

  def contact_us
  end

  private

  def set_limit
    # story_limit = Code.find_by(code_key: "LANDING_PAGE_STORY_COUNT").code_value
    @story_limit = current_user&.has_basic_access? ? 75 : 36
  end
end

app/views/home/_filters.html.erb
<%= form_tag(filter_path, method: :post) do %>
  <div class="row filters">
    <div class="col-12 col-sm-6 col-md-3 mb-1 mb-md-2">
      <%=
        select_tag :story_region_id,
        options_from_collection_for_select(@story_regions, 'id', 'name', params[:story_region_id]),
        prompt: 'All Story Regions',
        class: 'form-control form-control-sm',
        id: 'story-region-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mb-1 mb-md-2">
      <%=
        select_tag :place_grouping_id,
        options_from_collection_for_select(@place_groupings, 'id', 'name', params[:place_grouping_id]),
        prompt: 'All Place Types',
        class: 'form-control form-control-sm',
        id: 'place-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mb-1 mb-md-2">
      <%=
        select_tag :story_category_id,
        options_from_collection_for_select(@story_categories, 'id', 'name', params[:story_category_id]),
        prompt: 'All Story Categories',
        class: 'form-control form-control-sm',
        id: 'category-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mb-1 mb-md-0">
      <%= submit_tag "Filter", class: 'btn btn-sm btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/home/about_us.html.erb
<div class="container-sm">
  <div class="jumbotron bg-white about-us">
    <div class="header text-center">
      <h4>A Little About</h4>
      <%= image_pack_tag "sap-logo.png", id: "logo", class: "m-auto" %>
    </div>

    <hr class="my-4">

    <div class="body">
      <p class="lead text-center font-italic">
        We connect you to stories about (you guessed it) places!
      </p>
      <p>
        Do you love reading stories about unique and interesting places? The media loves writing stories about them, as you can find them in hundreds of media sources.
      </p>
      <p>
        But you probably don’t have time every day to visit hundreds of websites to find stories about unique and interesting places, and that means you’re missing out, including missing out on stories about places nearby.
      </p>
      <p>
        We curate stories from hundreds of media sources and make them easier to find. We’re still new, so our own story is not yet fully written, but we hope you enjoy what we’re doing, and if so please tell others to check us out too.
      </p>
      <p>
        New stories are added throughout the day, and there are lots more features and improvements we plan on adding. So don’t forget to keep checking back to see what’s new!
      </p>
      <p class="text-center">
        Thank you - The <strong>Stories About Places</strong> Team
      </p>
    </div>

    <hr class="my-4">

    <div class="footer text-center">
      Any other questions? <strong><%= link_to "Contact us!", contact_us_path %></strong>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<div class="container-sm">
  <div class="jumbotron bg-white about-us">
    <div class="header text-center">
      <h4>Contact The Team At</h4>
      <%= image_pack_tag "sap-logo.png", id: "logo", class: "m-auto" %>
    </div>

    <hr class="my-4">

    <div class="body">
      <p class="lead text-center">
        We really do want your feedback about our concept and our execution. Drop us an email.
      </p>
      <p class="text-center">
        <a href="mailto:contactus@storiesaboutplaces.com">
          contactus@storiesaboutplaces.com
        </a>
      </p>
    </div>

    <hr class="my-4">

    <div class="footer text-center">
      Curious about who we are and what we do? <strong><%= link_to "Learn more!", about_us_path %></strong>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid" id="main-content">
  <%= render partial: 'filters', locals: { filter_path: home_index_path } %>

  <div class="grid story-grid">
    <div class="grid-sizer"></div>
    <div class="gutter-sizer"></div>
    <% if @published_items.present? %>
      <% @published_items.each do |published_item| %>
        <% if published_item.publishable.type.in?(['MediaStory', 'VideoStory']) %>
          <%= render partial: 'shared/video_and_media_story_card', locals: { story: published_item.publishable, card_id: published_item.id, scope: nil } %>
        <% else %>
          <%= render partial: 'shared/custom_stories/card', locals: { story: published_item.publishable, card_id: published_item.id, scope: nil } %>
        <% end %>
      <% end %>
    <% else %>
      <p class="no-stories-text">No Stories Found</p>
    <% end %>
  </div>
</div>