config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root 'home#index'
  # DEVISE STUFF
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # UPDATE USER
  resources :users, only: [:edit, :update]
  # HOME CONTROLLER
  resources :home, only: [:index] do
    collection do
      post :index
    end
  end
  get 'about_us', to: 'home#about_us', as: :about_us
  get 'contact_us', to: 'home#contact_us', as: :contact_us
  # STORY ACTIONS
  resources :stories, only: [] do
    collection do
      get :view
    end
    member do
      post :save
      post :forget
    end
  end
  resources :sessions, only: :toggle_sidebar_state do
    collection do
      post :toggle_sidebar_state
    end
  end
  # MY STORIES
  get 'my_stories', to: 'stories#my_stories'
  # ADMIN ROUTES
  namespace :admin do
    resources :initialize_scraper, only: [:index] do
      collection do
        get :scrape
      end
    end
    resources :stories, only: [:index, :show, :destroy] do
      member do
        get :images
        post :images_update
        get :review
        patch :review_update
        patch :update_state
      end

      collection do
        get :bulk_index
        post :bulk_update
      end
    end
    resources :media_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :video_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :custom_stories, except: [:index, :destroy] do
      member do
        post :destroy_image
        get :list_editor
        get :list_edit
        patch :update_list
        get :review
        patch :review_update
      end
    end
    resources :urls, except: [:show]
    resources :images, except: [:show]
    resources :codes, except: [:show]
    resources :story_regions, except: [:show]
    resources :place_groupings, except: [:show]
    resources :story_categories, except: [:show]
    resources :media_owners, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :bulk_update
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :export_allstories
        get :export_stories
        get :export_images
        get :export_mediaowners
        get :export_usersaved
        get :export_userlisting
        get :export_all
        get :export_newsfeed_activities
      end
    end
    resources :published_items, except: [:show] do
      member do
        post :display
        post :unpublish
        post :add_to_queue
      end
    end
    resources :newsfeed, only: [:edit, :update] do
      member do
        post :remove
        post :publish
      end

      collection do
        get :queue
        get :activities
      end
    end
    resources :admin_settings, only: [:index, :update]
  end

  # redirect to home if route doesn't exist
  if Rails.env.production?
    match '*path', via: :all, to: 'home#index', constraints: lambda { |req|
      # NEED THIS HERE FOR ACTIVE STORAGE IMAGES TO SHOW UP
      req.path.exclude? 'rails/active_storage'
    }
  end
end

app/models/place_grouping.rb
class PlaceGrouping < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :place_groupings_stories, dependent: :destroy
  has_many :stories, through: :place_groupings_stories
end

app/controllers/admin/place_groupings_controller.rb
class Admin::PlaceGroupingsController < Admin::BaseAdminController
  before_action :set_grouping, except: [:index, :new, :create]
  before_action :check_for_admin, only: :destroy

  def index
    @groupings = PlaceGrouping.order(created_at: :desc)
    @groupings = @groupings.where("LOWER(code) ~ ?", params[:code].downcase) if params[:code].present?
    @groupings = @groupings.where("LOWER(name) ~ ?", params[:name].downcase) if params[:name].present?

    @pagy, @groupings = pagy(@groupings)
  end

  def new
    @grouping = PlaceGrouping.new
  end

  def create
    @grouping = PlaceGrouping.new(grouping_params)

    if @grouping.save
      redirect_to admin_place_groupings_path, notice: "Successfully created Place Grouping."
    else
      redirect_to admin_place_groupings_path, alert: "Could not create Place Grouping."
    end
  end

  def edit
  end

  def update
    if @grouping.update(grouping_params)
      redirect_to edit_admin_place_grouping_path(@grouping), notice: "Successfully updated Place Grouping."
    else
      redirect_to edit_admin_place_grouping_path(@grouping), alert: "Could not update Place Grouping."
    end
  end

  def destroy
    if @grouping.destroy
      redirect_to admin_place_groupings_path, notice: "Successfully destroyed Place Grouping."
    else
      redirect_to admin_place_groupings_path, alert: "Could not destroy Place Grouping."
    end
  end

  private

  def set_grouping
    begin
      @grouping = PlaceGrouping.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_place_groupings_path
    end
  end

  def grouping_params
    params.require(:place_grouping).permit(:code, :name)
  end
end

app/views/admin/place_groupings/_filters.html.erb
<%= form_tag(filter_path, method: :get) do %>
  <div class="row filters">
    <div class="col-12 col-sm-4 mt-1 mt-sm-0">
      <%= text_field_tag :name, params[:name], placeholder: 'Search Name...', maxlength: 100, size: 100, class: "form-control form-control-sm search-field" %>
    </div>
    <div class="col-12 col-sm-4 mt-1 mt-sm-0">
      <%= text_field_tag :code, params[:code], placeholder: 'Search Code...', maxlength: 100, size: 100, class: "form-control form-control-sm search-field" %>
    </div>
    <div class="col-12 col-sm-4 mt-1 mt-sm-0">
      <%= submit_tag "Filter", class: 'btn btn-sm btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/place_groupings/edit.html.erb
<div class="container">
  <%= form_for(@grouping, url: admin_place_grouping_path(@grouping)) do |f| %>
    <div class="jumbotron bg-white admin-form">
      <div class="header text-center">
        <h4><i class="fas fa-map-marked-alt mr-1"></i> Edit Place Grouping</h4>
      </div>

      <hr class="my-4">

      <div class="body">
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :code %><br>
          <%= f.text_field :code, class: "form-control" %>
        </div>

        <hr class="my-4">

        <div class="actions">
          <%= f.submit "Save", class: 'btn btn-md btn-primary text-center w-100' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/place_groupings/index.html.erb
<div class="container-fluid">
  <div class="links mb-2 text-right">
    <%= link_to new_admin_place_grouping_path, class: "btn btn-sm btn-success" do %>
      <i class="fas fa-plus mr-1"></i> Add Place Grouping
    <% end %>
  </div>
  <div class="jumbotron bg-white admin-index-page">
    <div class="header text-center">
      <h4><i class="fas fa-map-marked-alt mr-1"></i> Place Groupings</h4>
    </div>

    <hr class="my-4">

    <%= render partial: 'filters', locals: { filter_path: admin_place_groupings_path } %>

    <hr class="my-4">

    <div class="table-div">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
            <th scope="col">Created At</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @groupings.each do |category| %>
            <tr>
              <td><%= category.id %></td>
              <td><%= category.name %></td>
              <td><%= category.code %></td>
              <td><%= pretty_date_format(category.created_at) %></td>
              <td class="action-links">
                <%= link_to edit_admin_place_grouping_path(category), class: "btn btn-sm btn-outline-warning" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to admin_place_grouping_path(category), method: :delete, class: "btn btn-sm btn-outline-danger delete-link", data: { confirm: 'Are you sure?' }, target: '_blank' do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr class="my-4">

    <div class='pagination'>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/admin/place_groupings/new.html.erb
<div class="container">
  <%= form_for(@grouping, url: admin_place_groupings_path(@grouping)) do |f| %>
    <div class="jumbotron bg-white admin-form">
      <div class="header text-center">
        <h4><i class="fas fa-map-marked-alt mr-1"></i> Add Place Grouping</h4>
      </div>

      <hr class="my-4">

      <div class="body">
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :code %><br>
          <%= f.text_field :code, class: "form-control" %>
        </div>

        <hr class="my-4">

        <div class="actions">
          <%= f.submit "Save", class: 'btn btn-md btn-primary text-center w-100' %>
        </div>
      </div>
    </div>
  <% end %>
</div>