config/routes.rb
Rails.application.routes.draw do
  # ROOT
  root 'home#index'
  # DEVISE STUFF
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations"
  }
  # UPDATE USER
  resources :users, only: [:edit, :update]
  # HOME CONTROLLER
  resources :home, only: [:index] do
    collection do
      post :index
    end
  end
  get 'about_us', to: 'home#about_us', as: :about_us
  get 'contact_us', to: 'home#contact_us', as: :contact_us
  # STORY ACTIONS
  resources :stories, only: [] do
    collection do
      get :view
    end
    member do
      post :save
      post :forget
    end
  end
  resources :sessions, only: :toggle_sidebar_state do
    collection do
      post :toggle_sidebar_state
    end
  end
  # MY STORIES
  get 'my_stories', to: 'stories#my_stories'
  # ADMIN ROUTES
  namespace :admin do
    resources :initialize_scraper, only: [:index] do
      collection do
        get :scrape
      end
    end
    resources :stories, only: [:index, :show, :destroy] do
      member do
        get :images
        post :images_update
        get :review
        patch :review_update
        patch :update_state
      end

      collection do
        get :bulk_index
        post :bulk_update
      end
    end
    resources :media_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :video_stories, except: [:index, :destroy] do
      collection do
        get :scrape
      end
    end
    resources :custom_stories, except: [:index, :destroy] do
      member do
        post :destroy_image
        get :list_editor
        get :list_edit
        patch :update_list
        get :review
        patch :review_update
      end
    end
    resources :urls, except: [:show]
    resources :images, except: [:show]
    resources :codes, except: [:show]
    resources :story_regions, except: [:show]
    resources :place_groupings, except: [:show]
    resources :story_categories, except: [:show]
    resources :media_owners, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :bulk_update
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :export_allstories
        get :export_stories
        get :export_images
        get :export_mediaowners
        get :export_usersaved
        get :export_userlisting
        get :export_all
        get :export_newsfeed_activities
      end
    end
    resources :published_items, except: [:show] do
      member do
        post :display
        post :unpublish
        post :add_to_queue
      end
    end
    resources :newsfeed, only: [:edit, :update] do
      member do
        post :remove
        post :publish
      end

      collection do
        get :queue
        get :activities
      end
    end
    resources :admin_settings, only: [:index, :update]
  end

  # redirect to home if route doesn't exist
  if Rails.env.production?
    match '*path', via: :all, to: 'home#index', constraints: lambda { |req|
      # NEED THIS HERE FOR ACTIVE STORAGE IMAGES TO SHOW UP
      req.path.exclude? 'rails/active_storage'
    }
  end
end

app/models/published_item.rb
# frozen_string_literal: true

class PublishedItem < ApplicationRecord
  include AASM

  belongs_to :publishable, polymorphic: true

  validates :publishable_id, uniqueness: { scope: :publishable_type }

  aasm column: :state do
    state :displaying, initial: true
    state :queued
    state :newsfeed

    event :queue do
      transitions from: :displaying, to: :queued, after: proc { |*_args| update_after_queue }
    end

    event :remove do
      transitions from: :queued, to: :displaying, after: proc { |*_args| update_after_remove }
    end

    event :post do
      transitions from: :queued, to: :newsfeed, after: proc { |*_args| update_after_post }
    end

    event :clear do
      transitions from: :newsfeed, to: :displaying, after: proc { |*_args| update_after_clear }
    end
  end

  def self.all_states
    aasm.states.map { |x| x.name.to_s }
  end

  def update_after_queue
    last_queue_position = PublishedItem.where(state: 'queued').pluck(:queue_position).max || 0
    update(queue_position: last_queue_position + 1, queued_at: Time.zone.now)
  end

  def update_after_remove
    position_was_set = queue_position.present?
    update(queue_position: nil, queued_at: nil)
    PublishedItem.resequence_all_queue_positions if position_was_set
  end

  def update_after_post
    position_was_set = queue_position.present?
    track_post
    run_pinned_action_sequence if pinned?
    update(queue_position: nil, queued_at: nil, pinned_action: nil, posted_at: Time.zone.now)
    PublishedItem.resequence_all_queue_positions if position_was_set
  end

  def update_after_clear
    track_clear
    update(posted_at: nil, pinned: false)
  end

  def self.resequence_all_queue_positions
    sorted_by_position = PublishedItem.where(state: 'queued').where.not(queue_position: nil).order(
      queue_position: :asc, updated_at: :desc
    )
    sorted_by_position.each_with_index do |queued_item, index|
      new_position = index + 1
      queued_item.update(queue_position: new_position)
    end
  end

  def run_pinned_action_sequence
    old_pinned_item = PublishedItem.where(pinned: true).where.not(id: id).order(:posted_at).last
    return unless old_pinned_item

    # track pinned length
    track_unpin(old_pinned_item)

    if pinned_action.blank? || pinned_action == 'release'
      # trick the system to move it through natrually (by posted_at)
      old_pinned_item.update(posted_at: Time.zone.now, pinned: false, pinned_action: nil)
    else
      # replace the old pinned item
      old_pinned_item.clear!
    end
  end

  def track_unpin(old_pinned_item)
    time_pinned = old_pinned_item.posted_at ? Time.zone.now.to_time - old_pinned_item.posted_at.to_time : 0

    NewsfeedActivity.create!(
      trackable_id: old_pinned_item.publishable_id,
      trackable_type: old_pinned_item.publishable_type,
      posted_at: old_pinned_item.posted_at,
      activity_type: 'unpin',
      pinned: false,
      pinned_action: pinned_action,
      time_pinned: time_pinned,
      details: "Unpinned item. Action: #{pinned_action}"
    )
  end

  def track_post
    action = pinned ? pinned_action : nil

    NewsfeedActivity.create(
      trackable_id: publishable_id,
      trackable_type: publishable_type,
      activity_type: 'post',
      pinned: pinned,
      pinned_action: action,
      posted_at: Time.zone.now,
      time_queued: Time.zone.now.to_time - queued_at.to_time,
      details: 'Posted into newsfeed from queue.'
    )
  end

  def track_clear
    NewsfeedActivity.create(
      trackable_id: publishable_id,
      trackable_type: publishable_type,
      activity_type: 'clear',
      posted_at: posted_at,
      cleared_at: Time.zone.now,
      time_posted: Time.zone.now.to_time - posted_at.to_time,
      details: 'Removed from the newsfeed.'
    )
  end
end

app/controllers/admin/published_items_controller.rb
class Admin::PublishedItemsController < Admin::BaseAdminController
  before_action :set_published_item, only: [:display, :unpublish, :edit, :update, :add_to_queue]

  def index
    @story_regions    = StoryRegion.order("ascii(name)")
    @place_groupings  = PlaceGrouping.order(:name)
    @story_categories = StoryCategory.order(:name)

    @published_items = PublishedItem.joins("
      INNER JOIN stories ON (publishable_type = 'Story' AND stories.id = publishable_id)
      LEFT JOIN urls ON urls.story_id = stories.id
      LEFT JOIN stories_users ON stories_users.story_id = stories.id
      LEFT JOIN stories_story_regions ON stories_story_regions.story_id = stories.id
      LEFT JOIN story_regions ON story_regions.id = stories_story_regions.story_region_id
      LEFT JOIN place_groupings_stories ON place_groupings_stories.story_id = stories.id
      LEFT JOIN place_groupings ON place_groupings.id = place_groupings_stories.place_grouping_id
      LEFT JOIN story_story_categories ON story_story_categories.story_id = stories.id
      LEFT JOIN story_categories ON story_categories.id = story_story_categories.story_category_id
    ").select(
      'published_items.*',
      'stories.type AS story_type',
      "
        CASE
          WHEN stories.story_year > 0 AND stories.story_month > 0 AND stories.story_date > 0
          THEN TO_DATE(CONCAT(stories.story_year::TEXT, '-', stories.story_month::TEXT, '-', stories.story_date::TEXT), 'YYYY-MM-DD')
          WHEN stories.story_year > 0 AND stories.story_month > 0
          THEN TO_DATE(CONCAT(stories.story_year::TEXT, '-', stories.story_month::TEXT), 'YYYY-MM')
          ELSE null
        END AS story_date_combined
      "
    )
    @published_items = @published_items.where(state: 'displaying')
    @published_items = @published_items.where("LOWER(urls.url_title) ~ ?", params[:url_title].downcase) if params[:url_title].present?
    @published_items = @published_items.where("LOWER(urls.url_desc) ~ ?", params[:url_desc].downcase) if params[:url_desc].present?
    @published_items = @published_items.where("stories.type ~ ?", params[:story_type]) if params[:story_type].present?
    @published_items = @published_items.where(story_regions: {id: params[:story_region_id]}) if params[:story_region_id].present?
    @published_items = @published_items.where(place_groupings: {id: params[:place_grouping_id]}) if params[:place_grouping_id].present?
    @published_items = @published_items.where(story_categories: {id: params[:story_category_id]}) if params[:story_category_id].present?
    @published_items = @published_items.distinct
    @published_items = @published_items.order(story_date_combined: :desc)

    @pagy, @published_items = pagy(@published_items)
  end

  def add_to_queue
    if @published_item.queue!
      redirect_to admin_published_items_path, notice: 'Published Item was successfully added to the queue.'
    else
      redirect_to admin_published_items_path, alert: 'Published Item failed to be queued.'
    end
  end

  def display
    if @published_item.post!
      redirect_to admin_published_items_path, notice: 'Published Item was successfully displayed.'
    else
      redirect_to admin_published_items_path, alert: 'Published Item failed to be displayed.'
    end
  end

  def unpublish
    if @published_item.publishable.remove!
      redirect_to admin_published_items_path, notice: 'Published Item was successfully unpublished.'
    else
      redirect_to admin_published_items_path, alert: 'Published Item failed to be unpublished.'
    end
  end

  def edit
  end

  def update
    if @published_item.update(update_params)
      redirect_to admin_published_items_path, notice: 'Published Item was successfully updated.'
    else
      redirect_to admin_published_items_path, alert: 'Published Item failed to be updated.'
    end
  end

  private

  def set_published_item
    begin
      @published_item = PublishedItem.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to admin_published_items_path, alert: 'Published Item not found.'
    end
  end

  def bulk_update_params
    params.permit(:update_type, ids: [])
  end

  def update_params
    params.require(:published_item).permit(:clear_at, :pinned, :pinned_action)
  end
end

app/views/admin/published_items/_filters.html.erb
<%= form_tag(filter_path, method: :get) do %>
  <div class="row filters">
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-0">
      <%= text_field_tag :url_title, params[:url_title], placeholder: 'Search Title...', maxlength: 100, size: 100, class: "form-control form-control-sm search-field" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-0">
      <%= text_field_tag :url_desc, params[:url_desc], placeholder: 'Search Description...', maxlength: 100, size: 100, class: "form-control form-control-sm search-field" %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-0">
      <%=
        select_tag :story_type,
        options_from_collection_for_select(['MediaStory', 'VideoStory', 'CustomStory'], 'to_s', 'to_s', params[:publishable_type]),
        include_blank: 'All Story Types',
        class: 'form-control form-control-sm',
        id: 'story-type-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-0">
      <%=
        select_tag :story_region_id,
        options_from_collection_for_select(@story_regions, 'id', 'name', params[:story_region_id]),
        prompt: 'All Story Regions',
        class: 'form-control form-control-sm',
        id: 'story-region-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-1">
      <%=
        select_tag :place_grouping_id,
        options_from_collection_for_select(@place_groupings, 'id', 'name', params[:place_grouping_id]),
        prompt: 'All Place Types',
        class: 'form-control form-control-sm',
        id: 'place-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-1">
      <%=
        select_tag :story_category_id,
        options_from_collection_for_select(@story_categories, 'id', 'name', params[:story_category_id]),
        prompt: 'All Story Categories',
        class: 'form-control form-control-sm',
        id: 'category-select'
      %>
    </div>
    <div class="col-12 col-sm-6 col-md-3 mt-1 mt-md-1">
      <%= submit_tag "Filter", class: 'btn btn-sm btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/admin/published_items/edit.html.erb
<div class="container">
  <%= form_for(@published_item, url: admin_published_item_path(@published_item), method: :patch) do |f| %>
    <div class="jumbotron bg-white admin-form">
      <div class="header text-center">
        <h4><i class="fas fa-tasks mr-1"></i> Edit Published Item</h4>
      </div>

      <hr class="my-4">

      <div class="body">
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :clear_at %><br>
          <%= f.datetime_field :clear_at, class: "form-control" %>
        </div>

        <hr class="my-4">

        <div class="actions">
          <%= f.submit "Save", class: 'btn btn-md btn-primary text-center w-100' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/published_items/index.html.erb
<div class="container-fluid">
  <div class="jumbotron bg-white admin-stories admin-index-page">
    <div class="header text-center">
      <h4><i class="fas fa-tasks mr-1"></i> Publishable</h4>
    </div>

    <hr class="mt-3 mb-2">

    <%= render partial: 'filters', locals: { filter_path: admin_published_items_path } %>

    <hr class="mt-2 mb-3">

    <div class="table-div">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Regions</th>
            <th scope="col">Place Cat.</th>
            <th scope="col">Story Cat.</th>
            <th scope="col">Story Type</th>
            <th scope="col">Story Date</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @published_items.each_with_index do |published_item, index| %>
            <tr>
              <td style="width: 400px;">
                <% if published_item.pinned? %>
                  <i class='fa fa-star text-info'></i>
                <% end %>
                <%= link_to published_item.publishable.display_title, polymorphic_path([:admin, published_item.publishable]), target: '_blank', class: 'text-dark' %>
              </td>
              <td style="width: 200px;"><%= published_item.publishable.display_story_region_codes || '-' %></td>
              <td><%= published_item.publishable.display_place_groupings || '-' %></td>
              <td><%= published_item.publishable.display_story_categories || '-' %></td>
              <td style="width: 100px;">
                <i class='<%= colored_icon_for_story_type(published_item.story_type) %>'></i> <%= published_item.story_type.underscore.split("_").first.capitalize %>
              </td>
              <td style="width: 100px;"><%= published_item.story_date_combined %></td>
              <td style="width: 50px;">
                <%= link_to add_to_queue_admin_published_item_path(published_item), method: :post, class: "btn btn-sm btn-outline-success", data: { toggle: 'tooltip', placement: 'top', title: 'Add To Queue' } do %>
                  <i class="fas fa-plus"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr class="my-2">

    <div class='pagination'>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/admin/published_items/queue.html.erb
<div class="container-fluid">
  <div class="jumbotron bg-white admin-stories admin-index-page">
    <div class="header text-center">
      <h4><i class="fas fa-sort-numeric-down mr-1"></i> Newsfeed Queue</h4>
    </div>

    <hr class="my-4">

    <%= render partial: 'queue_filters', locals: { filter_path: queue_admin_published_items_path } %>

    <hr class="my-4">

    <div class="table-div">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Queue Position</th>
            <th scope="col">Display Position</th>
            <th scope="col">Pinned?</th>
            <th scope="col">Unpublish At</th>
            <th scope="col">Published Count</th>
            <th scope="col">Displaying Date</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% publish_day_count = 1 %>
          <% @published_items.each_with_index do |published_item, index| %>
            <tr>
              <td style="width: 600px;"><%= published_item.publishable.latest_url&.url_title %></td>
              <td><%= published_item.queue_position || '-' %></td>
              <td><%= published_item.position || '-' %></td>
              <td><%= human_bool(published_item.pinned) %></td>
              <td><%= published_item.unpublish_at&.strftime("%m/%d/%Y -  %I:%M %p")  || '-' %></td>
              <td><%= published_item.publishable.published_count %></td>
              <td><%= (Time.zone.now + publish_day_count.day).beginning_of_day.strftime("%m/%d/%Y") %></td>
              <td style="width: 100px;">
                <%= link_to queue_edit_admin_published_item_path(published_item), class: "btn btn-sm btn-outline-secondary m-1 w-100" do %>
                  <i class="fas fa-edit mr-1"></i> Edit
                <% end %>
                <%= button_to display_admin_published_item_path(published_item), class: "btn btn-sm btn-outline-success m-1 w-100", data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-upload mr-1"></i> Display Now
                <% end %>
                <%= button_to unpublish_admin_published_item_path(published_item), class: "btn btn-sm btn-outline-danger m-1 w-100", data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-times mr-1"></i> Unpublish
                <% end %>
              </td>
            </tr>

            <% publish_day_count += 1 if (index % PublishedItem.publish_rate) == (PublishedItem.publish_rate - 1) %>
          <% end %>
        </tbody>
      </table>
    </div>

    <hr class="my-4">

    <div class='pagination'>
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/admin/published_items/queue_edit.html.erb
<div class="container">
  <%= form_for(@published_item, url: queue_update_admin_published_item_path(@published_item)) do |f| %>
    <div class="jumbotron bg-white admin-form">
      <div class="header text-center">
        <h4><i class="fas fa-sort-numeric-down mr-1"></i> Edit Queued Item</h4>
      </div>

      <hr class="my-4">

      <div class="body">
        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :queue_position %><br>
          <%= f.number_field :queue_position, class: "form-control" %>
          <%= f.hidden_field :old_queue_position, value: @published_item.queue_position %>
        </div>

        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :position, 'Display position' %><br>
          <%= f.number_field :position, class: "form-control" %>
          <%= f.hidden_field :old_position, value: @published_item.position %>
        </div>

        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :unpublish_at %><br>
          <%= f.datetime_field :unpublish_at, class: "form-control" %>
        </div>

        <div class="form-group my-4 max-vw-80 mx-auto">
          <%= f.label :pinned %><br>
          <%= f.check_box :pinned %>
        </div>

        <hr class="my-4">

        <div class="actions">
          <%= f.submit "Save", class: 'btn btn-md btn-primary text-center w-100' %>
        </div>
      </div>
    </div>
  <% end %>
</div>